prometheus/graphite_exporter

Dockerfile

graphite_exporter has been migrated to github.com/prometheus/log, which
logs to stdout by default.

Remove -logtostderr from Dockerfile.

---

main.go

This PR sets the name of a metric in its help text to the name of the
Graphite metric. It should make writing mappings a lot easier as the
source name of a metric is now visible.

Set original name in help text of sample

---

Dockerfile
Makefile.COMMON
README.md
main.go

Following the docker related PR series.
New Dockerfile using the [alpine-golang-make-onbuild](https://github.com/sdurrheimer/alpine-golang-make-onbuild) base image whose goal is to unified the way to dockerize prometheus tools and exporters based on Golang.
The binary is build using make. (Golang is installed via make too, respecting the GO_VERSION).
A testable image is available under my name on Docker hub : [Link](https://registry.hub.docker.com/u/sdurrheimer/graphite-exporter/)
I have also added some Docker usage instructions in the readme.
As always, the [alpine-golang-make-onbuild](https://github.com/sdurrheimer/alpine-golang-make-onbuild)  image can be also move under Prometheus organization.
@brian-brazil @discordianfish

New Dockerfile using alpine-golang-make-onbuild base image

---

README.md
main.go

Hello there!
First of all, thanks for your work on this, it is a very useful tool :+1: 
We have a very large data set of metrics and we are trying to forward small subsets of metrics onto a different processing/analytics storage, but we don't want all the metrics. We only want those metrics that matches our mapping file configuration.
I added just a bunch of lines to enable that behaviour.
Cheers!

Add flag to drop metrics that don't match the mapping

---

mapper.go
mapper_test.go

Graphite metric names that begin with a dot '.' (ex. .*.*.test) are not mapped with respect to associated mapping defined in config file. See more details [here](https://github.com/prometheus/graphite_exporter/issues/13). In graphite, the initial dot is appended to the metric name when the user does not specify a group name for the metric.
I doubt users switching to Prometheus from Graphite would be interested in changing their metric names to include a group name as it would create a new time series without original time series' datapoints. Thus, this case can be handled by graphite_exporter with a small change to the regex that checks for valid mappings.

Allow mappings that begin with .

---

main.go

This is useful if there are many graphite exporters with
different settings.

Add metric returning sample expiry

---

main.go

For better trouble shooting, see https://github.com/prometheus/graphite_exporter/issues/57

Debug log incoming lines

---

main.go

Return 404 in the root HTTP handler iff the path is not "/" so that the
users would be able to access other end-points such as
"/debug/pprof/heap" and so on.
Unblocks work on issue https://github.com/prometheus/graphite_exporter/issues/66.

main: return 404 in the root HTTP handler iff path is not "/"

---

main.go
main_test.go

@matthiasr 
Fix issue #39 
Since pull request #52, graphite_Exporter use the statd_exporter.
A mapping label should now be able to be named "name". There's a check in main.go that prevent it.
I've remove the unwanted line.

Accept 'name' as a label

---

main.go

An FSM is not generated if you use a matching regex.
Signed-off-by: Joaquin Fernandez Campo <jfcampo@gmail.com>

Fixed panic on bad runtime flags.

---

main_benchmark_test.go

Adds a benchmark for the processLine function using the mock mapper.
Fixes #130 
Results on master:
```
$ go test -bench=.                                                                                                                             
goos: darwin
goarch: amd64
pkg: github.com/prometheus/graphite_exporter
BenchmarkProcessLine1-12           17187             69149 ns/op
BenchmarkProcessLine5-12            3506            343312 ns/op
BenchmarkProcessLine50-12            348           3451278 ns/op
PASS
ok      github.com/prometheus/graphite_exporter 4.920s
```

add benchmark for line processing

---

e2e/e2e_test.go
e2e/issue90_test.go

make e2e tests more reliable by giving more time for startup, adding sleep before getting metrics. This makes them much more reliable in my local testing, but probably isn't a perfect fix.
Fixes #87

make e2e tests more reliable

---

main_benchmark_test.go

Modify benchmarks to not measure startup costs - https://dave.cheney.net/high-performance-go-workshop/dotgo-paris.html#avoiding_benchmarking_start_up_costs
This doesn't seem to affect the benchmark results too much, but seems more correct.
@matthiasr

improve benchmark validity by not measuring startup costs

---

.golangci.yml
README.md
e2e/e2e_test.go
main.go
main_benchmark_test.go
main_test.go

Simple implementation of graphite tag support without breaking out into packages.
Fixes #36 
Benchmark on master:
```
$ go test -bench=. 
goos: darwin
goarch: amd64
pkg: github.com/prometheus/graphite_exporter
BenchmarkProcessLine1-12           17187             69149 ns/op
BenchmarkProcessLine5-12            3506            343312 ns/op
BenchmarkProcessLine50-12            348           3451278 ns/op
PASS
ok      github.com/prometheus/graphite_exporter 4.920s
```
Benchmark with tag parsing:
```
$ go test -bench=. 
goos: darwin
goarch: amd64
pkg: github.com/prometheus/graphite_exporter
BenchmarkProcessLine1-12           15975             75466 ns/op
BenchmarkProcessLine5-12            3189            374342 ns/op
BenchmarkProcessLine50-12            318           3767328 ns/op
PASS
ok …
```

simple graphite tags support

---

cmd/graphite_exporter/main.go

Fixes #31 
@matthiasr 
Signed-off-by: glightfoot <glightfoot@rsglab.com>

add check-config flag

---

README.md

Closes #165 #168.
Using this exporter together with the Graphite bridge (at least the one
in the Python client) does not work. Discourage trying this; point at
alternatives instead.
Signed-off-by: Matthias Rampke <matthias@prometheus.io>

Document incompatibility with Graphite bridge

---

reader/reader_test.go

The tests were time dependent, as the samples in the test data aged out
of the time window. In tests, override go-whisper's notion of "now" to a
fixed time that is close enough so that all data is within the maximum
retention window.
Signed-off-by: Matthias Rampke <matthias@prometheus.io>

Fix Whisper reader tests

---

cmd/graphite_exporter/main.go
e2e/e2e_test.go
e2e/fixtures/backtrack.yml

Fixes https://github.com/prometheus/graphite_exporter/issues/197.
Ensures that warnings from mapping are visible.
Add and end-to-end test that uses a backtracking configuration.

Pass a logger to the MetricMapper

---

cmd/getool/backfill_test.go
e2e/e2e_test.go
e2e/issue90_test.go

`ioutil` is deprecated from go1.16 (ref: https://go.dev/doc/go1.16#ioutil).
So removed them.
Signed-off-by: inosato <si17_21@yahoo.co.jp>

Remove ioutil

---

.circleci/config.yml

to fix issues with binfmt after the CircleCI infrastructure migration

Update Prometheus common orb

---

.golangci.yml
cmd/getool/backfill.go
cmd/getool/backfill_test.go
cmd/getool/main_test.go
cmd/graphite_exporter/main.go
collector/collector_benchmark_test.go
collector/collector_test.go
e2e/issue90_test.go
go.mod

* Since Dec 1, 2021, github.com/pkg/errors is an archived project.
* Since go 1.13, there is a standard errors and fmt modules that provides equivalent ways to handle errors.
Signed-off-by: Matthieu MOREL <matthieu.morel35@gmail.com>

use Go standard errors

---

.golangci.yml

`gofmt` is the common standard. It is good enough.

Remove gofumpt linter

---

cmd/getool/backfill_test.go
cmd/getool/main_test.go

Investigating #249, which remains mysterious.
Signed-off-by: Matthias Rampke <matthias@prometheus.io>

Add tests for Whisper conversion with mapping

---

MAINTAINERS.md

Pedro runs [one of the largest statsd-exporter
installations](https://promcon.io/2023-berlin/talks/taming-the-tsunami-low-latency-ingestion-of-push-based-metrics-in-prometheus/).
Considering how close the two exporters are, I am keeping maintainership in
sync.
Thank you Pedro for agreeing to help out!
Cf: https://github.com/prometheus/statsd_exporter/pull/594
Signed-off-by: Matthias Rampke <matthias@prometheus.io>

Add Pedro Tanaka as co-maintainer

---

cmd/getool/backfill.go
cmd/getool/backfill_test.go

When trying to import the generated blocks into Grafana Mimir, validation checks failed with an "out-of-order-labels" error.
This PR makes sure labels in the generated blocks are sorted and allows for the data to be backfilled using the mimirtool.
@matthiasr, @pedro-stanaka

Update backfill to generate blocks with sorted labels
